// src/app/pages/categories/categories.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FinanceStoreService } from '../../data/finance-store.service';

@Component({
  selector: 'app-categories',
  standalone: true,
  imports: [FormsModule],
  template: `
    <section class="categories">
      <header class="categories__header">
        <h1>Категории</h1>
        <p>Создавайте категории расходов и доходов.</p>
      </header>

      <form class="category-form" (ngSubmit)="handleAddCategory()">
        <label class="category-form__field">
          <span>Цвет</span>
          <input type="color" [(ngModel)]="categoryColor" name="categoryColor" />
        </label>

        <label class="category-form__field">
          <span>Название</span>
          <input
            type="text"
            placeholder="Например: Продукты"
            [(ngModel)]="categoryName"
            name="categoryName"
          />
        </label>

        <button class="category-form__submit" type="submit">Добавить</button>
      </form>

      <div class="categories__list">
        <p class="categories__empty" *ngIf="categories().length === 0">
          Категории пока не добавлены.
        </p>
        <ul *ngIf="categories().length > 0">
          <li class="category-card" *ngFor="let category of categories(); trackBy: trackCategory">
            <span class="category-card__color" [style.backgroundColor]="category.color"></span>
            <span class="category-card__name">{{ category.name }}</span>
          </li>
        </ul>
      </div>
    </section>
  `,
})
export class CategoriesComponent {
  readonly categories = this.store.categories;

  categoryName = '';
  categoryColor = '#3b82f6';

  constructor(private readonly store: FinanceStoreService) {}

  async handleAddCategory() {
    const trimmedName = this.categoryName.trim();

    if (!trimmedName) {
      return;
    }

    await this.store.addCategory({
      id: crypto.randomUUID(),
      name: trimmedName,
      color: this.categoryColor,
      type: 'expense',
      createdAt: new Date().toISOString(),
    });

    this.categoryName = '';
    this.categoryColor = '#3b82f6';
  }

  trackCategory(_: number, category: { id: string }) {
    return category.id;
  }
}

// src/routes/Categories.svelte
<script>
  import { addCategory, categories } from '../stores/financeStore';

  let categoryName = '';
  let categoryColor = '#3b82f6';

  const handleAddCategory = async () => {
    const trimmedName = categoryName.trim();

    if (!trimmedName) {
      return;
    }

    await addCategory({
      id: crypto.randomUUID(),
      name: trimmedName,
      color: categoryColor,
      type: 'expense',
      createdAt: new Date().toISOString(),
    });

    categoryName = '';
    categoryColor = '#3b82f6';
  };
</script>

<section class="categories">
  <header class="categories__header">
    <h1>Категории</h1>
    <p>Создавайте категории расходов и доходов.</p>
  </header>

  <form class="category-form" on:submit|preventDefault={handleAddCategory}>
    <label class="category-form__field">
      <span>Цвет</span>
      <input type="color" bind:value={categoryColor} aria-label="Цвет категории" />
    </label>

    <label class="category-form__field">
      <span>Название</span>
      <input
        type="text"
        placeholder="Например: Продукты"
        bind:value={categoryName}
        aria-label="Название категории"
      />
    </label>

    <button class="category-form__submit" type="submit">Добавить</button>
  </form>

  <div class="categories__list">
    {#if $categories.length === 0}
      <p class="categories__empty">Категории пока не добавлены.</p>
    {:else}
      <ul>
        {#each $categories as category (category.id)}
          <li class="category-card">
            <span class="category-card__color" style={`background-color: ${category.color}`}></span>
            <span class="category-card__name">{category.name}</span>
          </li>
        {/each}
      </ul>
    {/if}
  </div>
</section>
